DjangoBlog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
    path("", include("apps.posts.urls", namespace="posts")),
    path("", include("apps.users.urls", namespace="users")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoPosts/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
    path("", include("apps.posts.urls", namespace="posts")),
    path("", include("apps.users.urls", namespace="users")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/posts/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from apps.posts.views import (
    PostListView,
    PostDetailView,
    CreatePostView,
    UpdatePostView,
    DeletePostView
)

app_name = "posts"

urlpatterns = [
    path("posts/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("posts/", PostListView.as_view(), name="posts"),
    path("posts/create/", CreatePostView.as_view(), name="create-post"),
    path("update-post/", csrf_exempt(UpdatePostView.as_view()), name="update-post"),
    path("delete-post/", csrf_exempt(DeletePostView.as_view()), name="delete-post")
]

posts/urls.py
from django.urls import path

from posts.views import PostListView, PostDetailView

app_name = "posts"

urlpatterns = [
    path("posts/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("posts/", PostListView.as_view(), name="posts")
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import UserLogin, UserProfile

app_name = "users"

urlpatterns = [
    path("login/", UserLogin.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", UserProfile.as_view(), name="profile")
]

templates/base.html
{% load bootstrap4 %}
{% load fontawesome_5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Posts | {{ title }}</title>
    {% fontawesome_5_static %}
    {% bootstrap_css %}
    {% bootstrap_jquery %}
    {% bootstrap_javascript %}
    {% block styles %}
    {% endblock %}
</head>
<body>
{% include 'header.html' %}

{% block content %}

{% endblock %}
</body>
</html>

templates/header.html
{% load fontawesome_5 %}
<header>
    <!-- Шапка сайта -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <span class="navbar-brand">Django Posts | {{ title }}</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    {% if main_page %}
                        <span class="nav-link font-weight-bold active">Главная</span>
                    {% else %}
                        <a class="nav-link font-weight-bold" href="{% url 'posts:posts' %}">Главная</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    {% if create_post_page %}
                        <span class="nav-link font-weight-bold active">Создать пост</span>
                    {% else %}
                        <a class="nav-link font-weight-bold" href="{% url 'posts:create-post' %}">Создать пост</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    {% if profile_page %}
                        <span class="nav-link font-weight-bold active">Профиль</span>
                    {% else %}
                        <a class="nav-link font-weight-bold" href="{% url 'users:profile' %}">Профиль</a>
                    {% endif %}
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if not user.is_authenticated %}
                    <span class="font-weight-bold text-white">Пожалуйста, <a href={% url "users:login" %}>войдите</a> в аккаунт</span>
                {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="font-weight-bold text-white">{{ user.username }}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item text-dark-50" href={% url "users:profile" %}>
                                <i class="far fa-user"></i> Мой профиль
                            </a>
                            <form method="post" action={% url "users:logout" %}>
                                {% csrf_token %}
                                <button class="dropdown-item text-danger" type="submit">
                                    <i class="fas fa-sign-out-alt"></i> Выйти
                                </button>
                            </form>
                        </div>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>