DjangoBlog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
    path("", include("apps.posts.urls", namespace="posts")),
    path("", include("apps.users.urls", namespace="users")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoPosts/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
    path("", include("apps.posts.urls", namespace="posts")),
    path("", include("apps.users.urls", namespace="users")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from apps.users.views import (
    UserLoginView,
    UserProfileView,
    UpdateProfilePhotoView,
    UpdateProfileStatusView,
    UserRegistrationView
)

app_name = "users"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("registration/", UserRegistrationView.as_view(), name="registration"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("update-profile-photo/", csrf_exempt(UpdateProfilePhotoView.as_view()), name="update-profile-photo"),
    path("update-profile-status/", csrf_exempt(UpdateProfileStatusView.as_view()), name="update-profile-status")
]

posts/urls.py
from django.urls import path

from posts.views import PostListView, PostDetailView

app_name = "posts"

urlpatterns = [
    path("posts/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("posts/", PostListView.as_view(), name="posts")
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import UserLogin, UserProfile

app_name = "users"

urlpatterns = [
    path("login/", UserLogin.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", UserProfile.as_view(), name="profile")
]

apps/users/models/profile.py
from django.contrib.auth import get_user_model
from django.db import models, transaction
from django.db.models.signals import post_save
from django.dispatch import receiver

from apps.utils import (
    get_avatar_upload_path,
    validate_image
)

User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile", verbose_name="Пользователь")
    avatar = models.ImageField(upload_to=get_avatar_upload_path, default=None, blank=True, null=True,
                               verbose_name="Аватарка",
                               validators=[
                                   validate_image
                               ])
    status = models.CharField(max_length=128, default=None, blank=True, null=True, verbose_name="Статус")

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"
        ordering = ("pk",)

    def __str__(self):
        return str(self.user)

    def save(self, *args, **kwargs):
        if self.pk:
            old_instance = Profile.objects.get(pk=self.pk)
            if old_instance.avatar and self.avatar != old_instance.avatar:
                old_instance.avatar.delete(save=False)
        super().save(*args, **kwargs)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if not hasattr(instance, "profile"):
        with transaction.atomic():
            Profile.objects.create(user=instance)

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _

from apps.users.models import Profile


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update(
            {
                'class': 'form-control',
                'placeholder': _('Введите имя пользователя или email адрес'),
                'required': True,
                'minlength': 4,
                "maxlength": 32,
                "style": "border-radius: 10px;"
            }
        )
        self.fields["password"].widget.attrs.update(
            {
                'class': 'form-control',
                'placeholder': _('Введите пароль'),
                'required': True,
                'minlength': 6,
                'maxlength': 32,
                "style": "border-radius: 10px;"
            }
        )

        self.fields["username"].label = _("Имя пользователя/email адрес")
        self.fields["password"].label = _("Пароль")

    error_messages = {
        "invalid_login": _(
            "Неверный логин или пароль"
        ),
        "inactive": _(
            "Эта учетная запись неактивна"
        )
    }


class UpdateProfilePhotoForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["avatar"]
        widgets = {
            "avatar": forms.FileInput(attrs={'id': 'formFile', 'accept': '.jpg,.jpeg,.png'})
        }

apps/users/forms/update_profile_photo.py
from django import forms

from apps.users.models import Profile


class UpdateProfilePhotoForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["avatar"]
        widgets = {
            "avatar": forms.FileInput(attrs={'id': 'formFile', 'accept': '.jpg,.jpeg,.png'})
        }

apps/users/forms/user_login.py
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.error_messages.update(
            {
                "invalid_login": _(
                    "Неверный логин или пароль"
                ),
                "inactive": _(
                    "Эта учетная запись неактивна"
                )
            })

        self.fields["username"].widget.attrs.update(
            {
                'class': 'form-control form-widget',
                'placeholder': _('Введите имя пользователя или email адрес'),
                'required': True,
                'minlength': 4,
                "maxlength": 32
            }
        )
        self.fields["password"].widget.attrs.update(
            {
                'class': 'form-control form-widget',
                'placeholder': _('Введите пароль'),
                'required': True,
                'minlength': 6,
                'maxlength': 32
            }
        )

        self.fields["username"].label = _("Имя пользователя/email адрес")
        self.fields["password"].label = _("Пароль")

apps/users/forms/user_registration.py
import re

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserRegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.error_messages.update(
            {
                "password_mismatch": _("Пароли не совпадают")
            }
        )

        self.fields["username"].error_messages.update({
            "required": _("Поле является обязательным"),
            "unique": _("Имя пользователя уже используется")
        })

        self.fields["password1"].error_messages.update({
            "required": _("Поле является обязательным")
        })
        self.fields["password2"].error_messages.update({
            "required": _("Поле является обязательным")
        })

        self.fields["username"].widget.attrs.update({
            "minlength": 6,
            "maxlength": 16
        })

        self.fields["password1"].widget.attrs.update(
            {
                "class": "form-control form-widget",
                "placeholder": _("Пароль")
            }
        )
        self.fields["password2"].widget.attrs.update(
            {
                "class": "form-control form-widget",
                "placeholder": _("Подтвердите пароль")
            }
        )

    def clean_username(self):
        username = super().clean_username()
        if len(username) < 6:
            raise forms.ValidationError(_("Минимальная длина 6 символов"))
        if len(username) > 16:
            raise forms.ValidationError(_("Максимальная длина 16 символов"))
        if not re.fullmatch(r"^[A-Za-z][A-Za-z_.\\d]*[A-Za-z\\d]$", username):
            raise forms.ValidationError(_("Используйте только латинские символы и цифры"))
        return username

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ["username"]
        widgets = {
            "username": forms.TextInput(attrs={
                "class": "form-control form-widget",
                "required": True,
                "placeholder": _("Имя пользователя")
            })
        }

apps/users/views.py
import json

from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView

from apps.users.forms import (
    UserLoginForm,
    UpdateProfilePhotoForm,
    UserRegistrationForm
)
from apps.users.services import user_service


class UserRegistrationView(CreateView):
    form_class = UserRegistrationForm
    template_name = "users/registration.html"
    success_url = reverse_lazy("users:profile")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Registration"
        return context

    def form_valid(self, form):
        user = form.save(commit=True)
        login(self.request, user, backend="django.contrib.auth.backends.ModelBackend")
        return redirect(self.success_url)

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(self.success_url)
        return super().get(request, *args, **kwargs)


class UserLoginView(LoginView):
    authentication_form = UserLoginForm
    template_name = 'users/login.html'
    redirect_authenticated_user = True

    def post(self, request, *args, **kwargs):
        response = super().post(request, *args, **kwargs)
        remember_me = self.request.POST.get("remember-me", None)
        if remember_me is None:
            self.request.session.set_expiry(0)
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Login"
        return context

    def get_success_url(self):
        return reverse_lazy("posts:posts")


class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = "users/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.request.user.username
        context["profile_page"] = True
        context["user"] = self.request.user
        context["posts"] = self.request.user.posts.all()[:10]
        context["update_profile_photo_form"] = UpdateProfilePhotoForm(instance=self.request.user.profile)
        return context


class UpdateProfilePhotoView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        return user_service.update_photo(
            profile=self.request.user.profile,
            files=self.request.FILES,
            request=request
        )


class UpdateProfileStatusView(LoginRequiredMixin, View):
    def patch(self, request, *args, **kwargs):
        data = json.loads(self.request.body)
        status = data.get("status")
        return user_service.update_status(
            profile=request.user.profile,
            status=status
        )

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from users.forms import UserLoginForm


class UserLogin(LoginView):
    authentication_form = UserLoginForm
    template_name = 'users/login.html'
    redirect_authenticated_user = True

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["title"] = "Login"
        return data

    def get_success_url(self):
        return reverse_lazy("posts:posts")


class UserProfile(LoginRequiredMixin, TemplateView):
    template_name = "users/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.request.user.username
        context["profile_page"] = True
        context["user"] = self.request.user
        context["posts"] = self.request.user.posts.all()[:10]
        return context

templates/users/login.html
{% extends 'base.html' %}

{% block styles %}
    <style>
        .card,
        .login {
            border-radius: 10px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mt-3">
                    <div class="card-header">
                        <h3 class="text-center">Login</h3>
                    </div>
                    <div class="card-body">
                        <form method="post" action={% url "users:login" %}>
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    {% if field.errors %}
                                        {% for error in field.errors %}
                                            <div class="text-danger">
                                                {{ error }}
                                            </div>}
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            {% endfor %}
                            <div class="form-group">
                                <div class="row justify-content-end">
                                    <div class="col">
                                        <div class="form-group form-check d-flex align-items-center">
                                            <input type="checkbox" class="form-check-input" id="remember-me"
                                                   name="remember-me">
                                            <label class="form-check-label mb-0" for="remember-me">Запомнить
                                                меня</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% if form.non_field_errors %}
                                <div class="alert alert-danger text-center">
                                    {% for error in form.non_field_errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                            <button type="submit" class="btn btn-primary btn-block login">Войти</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load post_tags %}
{% load static %}
{% load tz %}

{% block styles %}
    <style>
        .profile-picture {
            width: 294px;
            height: 294px;
            border-radius: 50%;
            object-fit: cover;
            cursor: pointer;
        }

        .edit-profile {
            border-radius: 10px;
            margin-top: 10px;
        }

        .profile-column {
            margin-left: -100px;
            margin-right: 100px;
        }

        #user-status-js {
            word-wrap: break-word;
            white-space: pre-wrap;
        }

        #status-input-js {
            resize: none;
            overflow: hidden;
            border-radius: 10px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 mt-5 profile-column">
                {% if user.profile.avatar %}
                    <img src="{{ user.profile.avatar.url }}"
                         class="img-fluid profile-picture mb-2 ml-3"
                         alt="Фото профиля" data-toggle="modal" data-target="#uploadPhotoModal">
                {% else %}
                    <img src="{% static 'users/img/default-avatar.png' %}"
                         class="img-fluid profile-picture mb-2 ml-3"
                         alt="Фото профиля" data-toggle="modal" data-target="#uploadPhotoModal">
                {% endif %}
                {% if user.get_full_name %}
                    <h2 id="user-full-name">{{ user.get_full_name }}</h2>
                    <h6 class="text-muted" id="user-username">{{ user.username }}</h6>
                {% else %}
                    <h2 id="user-username">{{ user.username }}</h2>
                {% endif %}
                <p class="user-status" id="user-status-js">{{ user.profile.status|default_if_none:'' }}</p>
                <div class="text-danger" id="error-messages-js"></div>

                <div id="status-input-container-js" style="display: none;">
                    <textarea placeholder="О себе" class="form-control mb-3" id="status-input-js"
                              rows="1">{{ user.profile.status|default_if_none:'' }}</textarea>
                    <button class="btn btn-primary btn-sm" type="button" id="save-status-button-js">Сохранить</button>
                    <button class="btn btn-secondary btn-sm" type="button" id="cancel-save-status-button-js">Отменить
                    </button>
                </div>
                <button class="btn btn-primary btn-block edit-profile" id="edit-profile-js">Edit profile</button>
            </div>
            <div class="col-md-8 mt-5">
                {% if posts %}
                    <h3>10 последних постов</h3>
                    <div class="list-group">
                        {% for post in posts %}
                            <a href="{{ post.get_absolute_url }}" class="list-group-item list-group-item-action">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1" id="post-id-{{ post.id }}">
                                        {% publish_status post %}
                                        {{ post.title }}</h5>
                                </div>
                                <span class="text-muted">{{ post.created_at|timezone:"Europe/Moscow" }}</span>
                            </a>
                        {% endfor %}
                    </div>
                {% else %}
                    <h3>На данный момент вы не написали ни один пост &#9785;&#65039;</h3>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Модальное окно загрузки фото -->
    {% include 'modals/upload-photo.html' %}
    <script src="{% static 'users/js/upload-photo.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/autosize@4.0.2/dist/autosize.min.js"></script>
    <script src="{% static 'users/js/update-status.js' %}"></script>
{% endblock %}

templates/users/registration.html
{% extends 'base.html' %}

{% block styles %}
    <style>
        .card,
        .registration,
        .form-widget {
            border-radius: 10px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mt-3">
                    <div class="card-header">
                        <h3 class="text-center">Registration</h3>
                    </div>
                    <div class="card-body">
                        <form method="post" novalidate action={% url "users:registration" %}>
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    {% if field.errors %}
                                        {% for error in field.errors %}
                                            <div class="text-danger">
                                                {{ error }}
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            {% endfor %}
                            {% if form.non_field_errors %}
                                <div class="alert alert-danger text-center">
                                    {% for error in form.non_field_errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                            <button type="submit" class="btn btn-primary btn-block registration">Зарегистрироваться
                            </button>
                        </form>
                    </div>
                    <div class="text-center mt-3">
                        <p>Уже есть аккаунт?
                            <a href="{% url 'users:login' %}">Войти</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}